[package]
edition = "2021"
name = "farm_plugin_example"
version = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
farmfe_core = { version = "*" }
farmfe_toolkit_plugin_types = { version = "*" }
farmfe_macro_plugin = { version = "*" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }