[package]
edition = "2021"
name = "farmfe_plugin_vue_markdown"
version = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
farmfe_core = {version = "*"}
farmfe_macro_plugin = {version = "*"}
farmfe_toolkit = "0.0.11"
farmfe_toolkit_plugin_types = {version = "*"}
fervid = "0.2.0"
lazy_static = "1.5.0"
markdown-it = {version = "0.6.1", features = ["linkify"]}
markdown-it-front-matter = "0.3.0"
regex = "1.10.5"
serde_yaml = "0.9.34"
