[package]
edition = "2021"
name = "farmfe_plugin_vue_markdown"
version = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
farmfe_core = { version = "*" }
farmfe_toolkit_plugin_types = { version = "*" }
farmfe_macro_plugin = { version = "*" }
markdown-it = "0.6.1"
lazy_static = "1.5.0"
