/* generated by farmfe_plugin_auto_import */
export {} 
declare global {
	const getData: typeof import('./src/apis/auth/login.ts')['getData']
	const login: typeof import('./src/apis/auth/login.ts')['login']
	const getName: typeof import('./src/apis/index.ts')['getName']
	const useState: typeof import('react')['useState']
	const useCallback: typeof import('react')['useCallback']
	const useMemo: typeof import('react')['useMemo']
	const useEffect: typeof import('react')['useEffect']
	const useRef: typeof import('react')['useRef']
	const useContext: typeof import('react')['useContext']
	const useReducer: typeof import('react')['useReducer']
	const useOutletContext: typeof import('react-router')['useOutletContext']
	const useHref: typeof import('react-router')['useHref']
	const useInRouterContext: typeof import('react-router')['useInRouterContext']
	const useLocation: typeof import('react-router')['useLocation']
	const useNavigationType: typeof import('react-router')['useNavigationType']
	const useNavigate: typeof import('react-router')['useNavigate']
	const useOutlet: typeof import('react-router')['useOutlet']
	const useParams: typeof import('react-router')['useParams']
	const useResolvedPath: typeof import('react-router')['useResolvedPath']
	const useRoutes: typeof import('react-router')['useRoutes']
}
