/* generated by farmfe_plugin_auto_import */
export {} 
declare global {
	const getData: typeof import('./src/apis/index.ts')['getData']
	const useState: typeof import('react')['useState']
	const useCallback: typeof import('react')['useCallback']
	const useMemo: typeof import('react')['useMemo']
	const useEffect: typeof import('react')['useEffect']
	const useRef: typeof import('react')['useRef']
	const useContext: typeof import('react')['useContext']
	const useReducer: typeof import('react')['useReducer']
}
