[package]
edition = "2021"
name = "farmfe_plugin_wasm"
version = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
farmfe_core = { version = "*" }
farmfe_toolkit_plugin_types = { version = "*" }
farmfe_macro_plugin = { version = "*" }
farmfe_toolkit = { version = "*" }
rkyv = { version = "0.7.42" }
