[package]
edition = "2021"
name = "farmfe_plugin_yaml"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
farmfe_core = { workspace = true }
farmfe_toolkit_plugin_types = { workspace = true }
farmfe_macro_plugin = { workspace = true }
serde_yaml = "0.9.34"
lazy_static = "1.5.0"
serde = "1.0.203"
globset = "0.4.14"
regex = "1.10.5"
