[package]
edition = "2021"
name = "farmfe_plugin_modular_import"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
farmfe_core = { workspace = true }
farmfe_toolkit_plugin_types = { workspace = true }
farmfe_macro_plugin = { workspace = true }
serde = "1.0.197"
serde_json = "1.0.116"
regex = "1.10.6"
