name: Build Test
on:
  pull_request:
    branches:
      - main

jobs:
  call-rust-build:
    uses: ./.github/workflows/plugin-build.yaml
  examples-test:
    name: Examples Test
    runs-on: ${{ matrix.settings.os }}
    needs: [call-rust-build]
    strategy:
      fail-fast: false
      matrix:
        settings:
          - os: ubuntu-latest
            abi: linux-x64-gnu
          - os: macos-latest
            abi: darwin-arm64
          - os: macos-13
            abi: darwin-x64
          - os: windows-latest
            abi: win32-x64-msvc
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/download-artifact@v3
        with:
          path: /tmp/artifacts
      - name: Move Artifacts
        run: |
          for abi in linux-x64-gnu linux-x64-musl darwin-x64 win32-x64-msvc linux-arm64-musl linux-arm64-gnu darwin-arm64 win32-ia32-msvc win32-arm64-msvc
          do
               for package in dsv react-components virtual yaml strip image url icons
                do
                  folder_path="/tmp/artifacts/${{github.sha}}-${abi}-${package}"
                  if [ -d "${folder_path}"] && [ -n "$(ls -A $folder_path)"]; then
                    mv /tmp/artifacts/${{ github.sha }}-${abi}-${package}/* ./packages/${package}/npm/${abi}
                  fi
                done
          done
      - name: Install Dependencies
        run: npm install -g pnpm@9.1.0 && pnpm i --frozen-lockfile
      - name: E2E Test Examples - ${{ matrix.settings.abi }}
        run: npm run test-e2e
