name: Build Test
on:
  pull_request:
    branches:
      - main

jobs:
  call-rust-build:
    uses: ./.github/workflows/plugin-build.yaml
  call-js-build:
    uses: ./.github/workflows/js-plugin-build.yaml